replicaCount: 1

image:
  repository: mucsi96/spring-boot-demo-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

resources: 
  requests:
    memory: 500Mi
    cpu: 500m
  limits:
    memory: 1Gi
    cpu: 1000m

config:
  message: Hello from Spring Boot Demo!