- name: Install K3S
  hosts: cluster
  tasks:
    - name: Get SWAP file
      become: true
      ansible.builtin.shell:
        cmd: "cat /etc/fstab | grep swap | awk '{print $1}'"
      register: swap_file
      changed_when: false
    - name: Disable SWAP
      become: true
      ansible.builtin.command:
        cmd: swapoff --all
      when: ansible_swaptotal_mb > 0
    - name: Delete SWAP file
      become: true
      ansible.builtin.file:
        path: "{{ swap_file.stdout }}"
        state: absent
    - name: Remove swapfile from /etc/fstab
      become: true
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Install packages that allow apt to be used over HTTPS
      become: true
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: Add an apt signing key for Docker
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add apt repository for stable version
      become: true
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
    - name: Install docker and its dependecies
      become: true
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - Start Docker service
    - name: Add user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker

    - name: Download k3s install script
      become: true
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: ~/k3s_install.sh
        mode: a+x
    - name: Execute k3s_install.sh
      become: true
      ansible.builtin.shell: ./k3s_install.sh >> ./k3s_install_log.txt
      args:
        chdir: "~"
        creates: k3s_install_log.txt
      environment:
        INSTALL_K3S_VERSION: v1.25.3+k3s1 # https://github.com/k3s-io/k3s/releases
    - name: Load k3s config
      become: true
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kube_config
    - name: Parse k3s config
      ansible.builtin.set_fact:
        kube_config: "{{ kube_config.content | b64decode | from_yaml }}"
    - name: Create local k3s config
      ansible.builtin.copy:
        dest: .kube_config
        content: "{{ lookup('ansible.builtin.template', 'templates/kube-config.yml') }}"
        mode: 0444
      vars:
        certificate_authority_data: "{{ kube_config.clusters.0.cluster['certificate-authority-data'] }}"
        client_certificate_data: "{{ kube_config.users.0.user['client-certificate-data'] }}"
        client_key_data: "{{ kube_config.users.0.user['client-key-data'] }}"
      delegate_to: 127.0.0.1

  handlers:
    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
