Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"

    config.vm.define 'ubuntu'

    config.vm.network "private_network", ip: "192.168.33.10"

    # Prevent SharedFoldersEnableSymlinksCreate errors
    config.vm.synced_folder ".", "/vagrant", disabled: true
end