Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"

    config.vm.define 'ubuntu'

    config.vm.network "private_network", ip: "192.168.56.10"

    # Prevent SharedFoldersEnableSymlinksCreate errors
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.ssh.host = "192.168.56.10"
    config.ssh.port = 22
end