- name: Set cluster host
  ansible.builtin.set_fact:
    cluster_host: "{{ ansible_host }}"
- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: ansible-demos
- name: Add deployment and service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - deployment.yml
    - service.yml
    - ingress-route.yml
  vars:
    name: client
    namespace: ansible-demos
    image: mucsi96/ansible-demos-client:4
- name: Test a request to the service.
  ansible.builtin.uri:
    url: http://{{ cluster_host }}
    return_content: true
  register: this
  until: this.status == 200
  retries: 5
  delay: 1
  failed_when: "'Hello from Ansible Demo Page' not in this.content"
  delegate_to: localhost
- name: Print the URL for hello-k8s.
  ansible.builtin.debug:
    msg: http://{{ cluster_host }}
