apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-deployment
  namespace: nginx-demo
spec:
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: ssv
        ports:
        - containerPort: 80
      volumes:
        - name: ssv
          persistentVolumeClaim:
            claimName: nginx-demo-pvc