apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-demo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/shared/kubernetes-nginx-demo'
