apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-demo-pvc
  namespace: nginx-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
