app:
  message: ${env.MESSAGE}
server:
  shutdown: graceful
management:
  server:
    port: ${env.MANAGEMENT_SERVER_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://${env.MYSQL_HOST}:${env.MYSQL_PORT}/${env.MYSQL_DATABASE}?createDatabaseIfNotExist=true
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
    name: spring-boot-demo
  boot:
    admin:
      client:
        url: http://${env.ADMIN_SERVER_HOST}:${env.ADMIN_SERVER_PORT}