app:
  message: ${env.MESSAGE}
server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  health:
    probes:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://${env.MYSQL_HOST}:${env.MYSQL_PORT}/${env.MYSQL_DATABASE}?createDatabaseIfNotExist=true
#    url: jdbc:mysql://${env.MYSQL_HOST}:${env.MYSQL_PORT}/${env.MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true