{{- $fullName := include "helm-nginx-demo.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-websecure
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    services:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
