replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources: 
  limits:
    memory: 128Mi
    cpu: 100m

secrets:
  rootPassword: AgBxeZ3QR68JlO7BR2qA0c9xOBiwEsnTBHMClzEYDj7np51XjT4xQJYMCkYpfAz9Di1sMzCjj7iAQImLIwM/05hpKSR8qpu6rFWN6lZTz/0kOWjABojbKkwJMUZrZPbs06DsVlELoHH2WFTybgjKUANjhDu+dc9QEafKCoCWFm7rZ1ExXSgnkS3VAxpS6yp4JLEiANrw37XDvDLGnq+9T9qRFzVWkqjaSlOU7722fNY9OIQWHOgW/0UWNKVpeqTl2dVJgC3fzrG4Yh1HU57OJ/EIzhIBhU+xrFgz7Qb0P2G6vXOY0Klv7eLT7L2FeIkYkwF7qoyqQQ8Cl7AkvtDPiY8Y9tBC0Xev7RWS6rhJFTwolT5xCFdzX7bbaCpjnOddevwz456dHbcJks/rjDR0pe9FUb/nCGGipMFfG0jxlNBdJXLznJ2ZwQOeYZJFMg2aUtsz2aphf0tmY8x6W363rc7F+6F5RE4R6nhcLElE4e5tIX25pOU+db8ZvjzDX3rsHGnngTGEnUArQY04QtfNmzPZBhi9YHOLB7G16bv206Y7xVw5kzijTvCxrcA+aF63YMZ8xP0oXzXn9dUC0+2ry0LDvThOABFJTDuDBtv6E3hTx9b+4/9OHzxluIGYArsEFQy9c/mcgEyn6je93QKS9um6k/S+Ao66+5OcwwWLRLwG4g10KVaLHKJpWo+wPfFYXj04Df818jgivzySb65fxo/fE4UN3ccAZnATnJE=
  userName: AgDT3EqHV0yDG57jeCbBD0pH1NHoSsRnvDwONqw8C97ZOlVTcYKygombzLcU2BKBIFX72dUbio3zBaI9u+5bazYoTPdW5n9M9fcSpMTHQ1IgDjvWyOBS+SBrENvHWNDJtBANOPwoeU8n26oDgrvcbJYdVMAnkgcaYb/O7wWZV8oIyKwh6LR5ah2ew9qUt/GfBuhlyo8KdjEkOoX30OOoHgw7IFT26Y8+is0kzEUQxYDcC3MJkUGV70b9XvSgTg8ROHGflsxenaLdLQ+eYWPH3D5RhZ5LSsCL4mHIzi/EV6CUxb7gB7gkN7R6JUPfB0cef9CAIPdKGGZ1YhjYnc1vaBLhyvlFdl+kmOKWCavect/gmxhwPjE1fBY34v4wOIS2KZ9SSp7sKEgqgPSI2ic/GNH4JpdoKzQwIlfH2UDL7I8+avZyKkuTKncVkLc+mWfd3+W+NIlQNTrtcioPlm5/WsrMy2TtDvTfxUuVHIGav01Gd/oSu63CK095ysFw9N3UuvgIfqZQI4bhQZb+5jMBvELYGCeNSxhV3cr6I7WpPvejXRxPA0UvM9j/zit9aRcTsTluUmbthvy4z2nxRqiUI81adiBTu83lastrpAuy39ZGUq+p+01rQf9MD5WF9dxbqt0dD6K/pLeaUskjjPe9CQCNmp7aUuvIQYxtK6+Mm6Ag/oWHg3MkbU2WVJMagLMITgblc9QwtXZtkhE3mA==
  password: AgCHotS9FHLw77UVO4QGr/BxCu/7x/aDj1O6ta31iLzhTetd1BOgdn5mAYV+hpOUt21xJmYLNZ8uvLV6SY+TEx2jwFtiROoZHnd8HA8EMOXxwRi+0FKvBay2DKq5kE3HrvzAi3OpOfL630utJguKdDoewFt0eQLpZUs3uRPoEecouDh+vmyGLta8PY3Mgkm0PGZJF4jPYOFjcBjQMlVfMWnJDxc+B0tpD/tpINcB8wUGoqSnI+62HxN+AA0jtmqA7xcul0Nd8FPNLpZXADaAyJ82vO1d4qVKdaiCqOGOMXisHAnuWabO59EOfn0tVsimpVZO92ZzGZ3hpjRI1x+8yk//vv56cjp6PqNoTyp1PHOJfejKVD+/SiPS4dPY2DQyydYZBNgGPs6XuLOjM/JmWNMQ22NB9qQhIYSzPbC97xmd5H04sGn9Q8wZsG1RetJOePKYbdEHZrbzwS+wT8l+AEBYKrvYjlWF1/cZaqz7j017GmfPS1sCrNj7fZZPQhfR18lKFOgC8mwNzs4pXJpZFjSeJnNqye3y/jnf7mJe8OSCGZdglEyAGkNl4UzCMkFHz9i5qkuBDhiQe7sX9T6lEpgD7Xc+9TfaFe/KFMvPkjoPwCsSco6S46Qn+8wvNa3zTEFN9cPyF2IobwTOqsvg049YBrsMaWWBpQ257IhvoDwjdYDA9odFiKfV8QbKAU1t0LcIw+vPFEVX01Jp+f9YfMR7G92TWpKIQBVa9Vg=

config:
  databaseName: demo

    