replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources: 
  limits:
    memory: 900Mi
    cpu: 700m

secrets:
  rootPassword: AgCnF7iObru47Vn5mQOvN2QW+5TxOpdCC8jJ97xuyqzYcOLIpkZ7jfwrMcO0wl1ewbSOiGEo5BVgDH9ysKKMqjHa6dJ/qrHTAznfOuiHpHAGPTyQ9a9GXVstsuX5SNjgwesUInf5VZo40OQG9G36D94Uvvu/aiqtJYnqm4pufexTcVOQnI+BtJYIZKLptCWGLdU3wQ7TCr9Tp4cfPf9h0MCYY53HItpWyG880qLVIpIP2kcLlGe/vSbenBADbw/02gilZOlwlQP/1g5tctHzCj4HJj/bigx8C8rU4zLOa2QI79Re+7k7HT4y9wj3x0LN8cT12pdk2WNy6+06tllTsrVkrqJN4fhfDMcxFyK+LJMpZKQz0ew3mtKFyt4ZHoNtx2QnqhQUPT+J7kWa0JIvLpTfVEAqdcShVy8Q1LtO5vc94Nn2HZx1CRAnbMZOupk2K9zfL3RceAOexEGnvjMVZ+PHbV8gEO53J4vpL0CSsoFkUivynaXzDWLFfPHuV4BRXSJv1dotuedELmMP4dTOI7+KYuYJCnPdMNbfRnZS31PyOhTO9wwLRxDUva0IarhKWmtba660xRsN4o1MI/piIWO0974+Sj+o+Lx1VShoe+tLMFI2E1LhCOraNDYdKpxfzunRBl5v1dlFn9eHoAdeiXvKuA6jWJOhwsz6VOpPyzPbCLyVLvl8ADbBnF7zEWBnA96NdMTVn5FvyA9iQX13ace1Ll8=
  userName: AgDfraohF29z30mAfQAMhFazt/xJKf+b26i9Pr3BbEr719sZB+TilksanCwfvrNAf01qN5SfvhBqrxgaZmTiL1mdKpDBKYvhe1hfDVVfPs9xQWvM9fmb9gh1ezN4/NGT++qkXjpoj8hY1nu2onIJKspcm3tMRaFLop32DMSMYBdO0jSrBjIybyFfWkvfwu9LfW6bfTOuGv9C/VIpkOPPDzYUWSQIQhmLb1Pe73l/1QDI28PYVBPygfLiy9xV7B2RTQUKLQymi4z+dKjmuYN57zcAiiDod/nBLnSnOJnsCTIAPK9JJUePpIiUImbFmUfB0XBwe5pO/jjUZ8z31DOcUKjrgwzWQaeO0wsn+rXxuO84EW1M4ZzUmkmPoHtvituI8Jg+RLTULCuqQFJaEpOt/POZZlfKs4wMCltb7nWuHw4vDkXuW9GiIOqQtL0lnXGH1y6zm4Mjn/uGvL813INPJKe2Q3jVgH3fyggUmIfrWKnWHgA33jDNQtYBTNmaosqCUGiotFeaNhg+xxbrnqVzkmCKiLE+/qcw/N2Z2ul2/rDbsdfPYYnkZpwZLOLsE8RvtnIDt5rLvzEkJDWPn7ZTq5BBjI2tvMWUNY+mcHPqSAhS0qO/KqzBbuh70fiMyZswXoLQamXLhRB/ynpjuP1QvrMs3KeTFUkGSTk7kY0/g6+s9GjrhF+og7RDDRv81K2Rmj8PllkC35P+xoBG
  password: AgBumkMw24KDtZn/sRf5mM3rVjOHBnJwN+l9Lioc+a2CBI7uRR3lNQeWlCksculvRdw03SlTrDI1+U/jTCCqKrNxV2FxP2a3S4e1l/wRc89iMfIuiIBk/qt1/FVxU0dI/2w1iDKclDJ3aYKM0a4MyrNr3qPW0bRfgjoGHPI8PfEpr7yrg8aAU7Wh0Dscwt039PmYXd+CSAmmpO626FR6gdx9S8a5NTrxDu9/tajnLVTCQRboUNDZ5FQ37oucy1SdECM4ejjr7cdhAgx9j4jsKbR+Pk/m6HhGIld36a29x7rLH4aISmIWBGGyVrlWcaTLZbJbV59LxO2c61cEdHVGf0fVWkneVZ98n1wOW556Z04VR3G+AvnrlsFc7j3bKi6f7vx1kA5ruyLIIuZRtpngWPMWeV3tUzzc03yJ4EB9HZcc/SwgKSeexB7T8EZFDOUHTC2iNP8fmh3NbPHOxiLV+7fmKsWwf3JXWt4CRujiSaPp8VWURskvVYH5g7HAd+wQdlCygT/FHsSAFU1abQvGRQ+ijWtrScm5TAA624PfIubhUfAHXm7rmL4bcn8PjNGU456v8AIOqmFXKNynLYjENBgzGnpUVsOUyWonS21UAyVUDx4XI2M0IK6ksk2LhsAnzjdr0WfO0M0Bz4zFDjmZesbAvISAfsL8ovHLXmjDRwkNZvVn2b0tJPqrVUAaeSllyCT1OCADygvGWfTPTpPBkRaQ2qI=

config:
  databaseName: demo

    