- name: Download k3s install script
  become: true
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: ~/k3s_install.sh
    mode: a+x
- name: Execute k3s_install.sh
  become: true
  ansible.builtin.shell: ./k3s_install.sh >> ./k3s_install_log.txt
  args:
    chdir: "~"
    creates: k3s_install_log.txt
  environment:
    INSTALL_K3S_VERSION: v1.25.3+k3s1 # https://github.com/k3s-io/k3s/releases
- name: Load k3s config
  become: true
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kube_config
- name: Parse k3s config
  ansible.builtin.set_fact:
    kube_config: "{{ kube_config.content | b64decode | from_yaml }}"
- name: Create remote kubernetes config folder
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0770
- name: Create remote kubernetes config
  ansible.builtin.copy:
    dest: ~/.kube/config
    content: "{{ lookup('ansible.builtin.template', 'kube-config.yml') }}"
    mode: 0444
  vars:
    certificate_authority_data: "{{ kube_config.clusters.0.cluster['certificate-authority-data'] }}"
    client_certificate_data: "{{ kube_config.users.0.user['client-certificate-data'] }}"
    client_key_data: "{{ kube_config.users.0.user['client-key-data'] }}"
    host: 127.0.0.1
- name: Install pip3
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present
- name: Install kubernetes client
  ansible.builtin.pip:
    name:
      - kubernetes == 25.3.0