{{- $fullName := include "ingress.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-{{ $fullName }}-http-to-https@kubernetescrd
spec:
  rules:
   - host: {{ .Values.hostName }}
     http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.application.service.name }}
              port:
                number: {{ .Values.application.service.port }}