datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://${prometheus_host}
        access: proxy
        isDefault: true

dashboards:
  node-exporter-full:
    gnetId: 1860
    revision: 27
    datasource: Prometheus
  kubernetes-kubelet:
    gnetId: 12123
    revision: 1
    datasource: Prometheus
  traefik-2:
    gnetId: 11462
    revision: 1
    datasource: Prometheus
