{{- $fullName := include "app.fullname" . -}}
{{ $livenessPort := 8081 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - name: http
          containerPort: 8080
        - name: liveness-port
          containerPort: {{ $livenessPort }}
          hostPort: {{ $livenessPort }}
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: {{ $fullName }}
                key: message
          - name: MYSQL_DATABASE
            value: {{ required "Missing database.name value" .Values.database.name }}
          - name: MYSQL_HOST
            value: {{ required "Missing database.host value" .Values.database.host }}
          - name: MYSQL_PORT
            value: {{ required "Missing database.port value" .Values.database.port | quote }}
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: userName
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: password
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: {{ $livenessPort }}
        #   initialDelaySeconds: 15
        # startupProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: {{ $livenessPort }}
        #   initialDelaySeconds: 30
        #   failureThreshold: 30
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]