{{- $fullName := include "app.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullName }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    userName: {{ required .Values.database.userName }}
    password: {{ required .Values.database.password }}