apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.services.server.name }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.global.services.server.port }}