{{- $fullName := include "ingress.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-https
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ $fullName }}-ratelimit@kubernetescrd
spec:
  rules:
   - host: {{ .Values.hostName }}
     http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-{{ .Values.application.clientService.name }}
              port:
                number: {{ .Values.application.clientService.port }}
  tls:
  - secretName: {{ .Values.tls.secretName }}