{{- $fullName := include "ingress.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-client
spec:
  entryPoints: 
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.hostName }}`) && PathPrefix(`/`)
    middlewares:
    {{- include "ingress.commonMiddlewares" . | nindent 4 }}
    services:
    - kind: Service
      name: {{ .Release.Name }}-{{ .Values.global.services.client.name }}
      port: {{ .Values.global.services.client.port }}
  {{- include "ingress.tls" . | nindent 2 }}