name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring-boot-demo/scripts
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: terraform fmt
      - run: git diff
      - run: terraform fmt -check
      - name: Authenticate to Docker Hub
        run: |
            docker login \
              --username ${{ secrets.DOCKER_HUB_USERNAME }} \
              --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            cat ~/.docker/config.json
      - name: Authenticate to Kubernetes cluster
        run: |
            mkdir ~/.kube
            echo "${{ secrets.KUBERNETES_CLUSTER_CA_CERTIFICATE }}" > ~/.kube/cluster_ca_certificate.pem
            echo "${{ secrets.KUBERNETES_CLIENT_CERTIFICATE }}" > ~/.kube/client_certificate.pem
            echo "${{ secrets.KUBERNETES_CLIENT_KEY }}" > ~/.kube/client_key.pem
            kubectl config set-cluster appcluster \
              --server ${{ secrets.KUBERNETES_HOST }} \
              --certificate-authority ~/.kube/cluster_ca_certificate.pem
            kubectl config set-credentials appuser \
              --client-certificate ~/.kube/client_certificate.pem \
              --client-key ~/.kube/client_key.pem
            kubectl config set-context appcontext \
              --cluster appcluster \
              --user appuser
            kubectl config use-context appcontext
            cat ~/.kube/config
            kubectl get nodes
      - run: terraform init
      - run: |
            terraform apply -auto-approve -input=false \
              -var 'run_number=${{ github.run_number }}'
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Build and push client
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./spring-boot-demo/client
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-demo-client:${{ github.run_number }},${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-demo-client:latest
      # -
      #   name: Build and push server
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./spring-boot-demo/server
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-demo-server:${{ github.run_number }},${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-demo-server:latest