name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Docker Hub
        run: |
            docker login \
              --username ${{ secrets.DOCKER_HUB_USERNAME }} \
              --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Authenticate to Kubernetes cluster
        run: |
            mkdir ~/.kube
            echo "${{ secrets.KUBERNETES_CLUSTER_CA_CERTIFICATE }}" > ~/.kube/cluster_ca_certificate.pem
            echo "${{ secrets.KUBERNETES_CLIENT_CERTIFICATE }}" > ~/.kube/client_certificate.pem
            echo "${{ secrets.KUBERNETES_CLIENT_KEY }}" > ~/.kube/client_key.pem
            kubectl config set-cluster appcluster \
              --server ${{ secrets.KUBERNETES_HOST }} \
              --certificate-authority ~/.kube/cluster_ca_certificate.pem
            kubectl config set-credentials appuser \
              --client-certificate ~/.kube/client_certificate.pem \
              --client-key ~/.kube/client_key.pem
            kubectl config set-context appcontext \
              --cluster appcluster \
              --user appuser
            kubectl config use-context appcontext
      - name: Update versions
        run: ./version.sh
        working-directory: ./spring-boot-demo
      - name: Deploy
        run: |
            terraform fmt -check -diff
            terraform init
            terraform apply -auto-approve -input=false
        working-directory: ./spring-boot-demo/scripts