name: vagrant-up

on: [push]

jobs:
  local-ansible-deploy:
    runs-on: macos-12
    defaults:
      run:
        working-directory: ./ansible-kubernetes-demo
    steps:
      - uses: actions/checkout@v3

      - name: Cache Python requirements
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pip
          key: 1-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            1-${{ runner.os }}-pip-

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: 1-${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            1-${{ runner.os }}-vagrant-

      - name: Install Ansible
        run: brew install hudochenkov/sshpass/sshpass ansible

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: Show SSH Config
        run: vagrant ssh-config

      - name: Deploy
        run: ansible-playbook main.yml
