name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-12
    defaults:
      run:
        working-directory: ./ansible-kubernetes-demo
    steps:
      - uses: actions/checkout@v3

      - name: Cache Python requirements
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pip
          key: 1-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            1-${{ runner.os }}-pip-

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: 1-${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            1-${{ runner.os }}-vagrant-

      - name: Get Python cache working-directory
        run: pip3 cache dir

      - name: Install Python requirements
        run: pip3 install -r requirements.txt

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: Show SSH Config
        run: vagrant ssh-config
      
      - name: Install Kubernetes
        run: ansible-playbook -i inventory install-k3s.yml 
      
      - name: Install deployment
        run: ansible-playbook -i inventory install-deployment.yml 