{{- $fullName := include "app.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - name: http
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: rootPassword
          - name: MYSQL_DATABASE
            value: {{ required "Missing name value" .Values.name }}
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: userName
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: password
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: ssv
      volumes:
      - name: ssv
        persistentVolumeClaim:
          claimName: {{ $fullName }}
