{{- $fullName := include "app.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    rootPassword: {{ required "Missing rootPassword value" .Values.rootPassword }}
    userName: {{ required "Missing userName value" .Values.userName }}
    password: {{ required "Missing password value" .Values.password }}