{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  data:
    rootPassword: {{ required "Missing rootPassword value" .Values.rootPassword }}
    userName: {{ required "Missing userName value" .Values.userName }}
    password: {{ required "Missing password value" .Values.password }}