{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ required "Missing service.port value" .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None